import type { Categoria, Produto } from "./tipos";

/**
 * Data de referência do mock. Fixa de propósito: o histórico de vendas é
 * gerado a partir dela e precisa sair idêntico no servidor e no cliente,
 * senão a hidratação quebra.
 */
export const HOJE = new Date("2026-08-05T12:00:00.000Z");

export const CATEGORIAS: Categoria[] = [
  {
    id: "consoles",
    nome: "Consoles",
    descricao: "PlayStation, Xbox e edições de lançamento",
  },
  {
    id: "celulares",
    nome: "Celulares",
    descricao: "iPhone, Galaxy, Xiaomi e Motorola",
  },
  {
    id: "notebooks",
    nome: "Notebooks",
    descricao: "Gamer, trabalho e ultrafinos",
  },
  { id: "audio", nome: "Áudio", descricao: "Caixas JBL, fones e headsets" },
  {
    id: "acessorios",
    nome: "Acessórios",
    descricao: "Controles, headsets e periféricos",
  },
];

export const PRODUTOS: Produto[] = [
  {
    id: "p01",
    slug: "console-ps5-slim-1tb-2-controles",
    sku: "8412-PS5",
    nome: "Console PlayStation 5 Slim 1TB + 2 Controles",
    marca: "Sony",
    categoria: "consoles",
    forma: "console",
    precoDe: 4599,
    preco: 3499,
    custo: 2890,
    estoque: 42,
    estoqueAlvo: 60,
    nota: 4.9,
    avaliacoes: 1284,
    selos: ["mais-vendido", "frete-gratis"],
    resumo:
      "O PS5 Slim com 1TB de SSD e dois controles DualSense na caixa. Jogo em 4K a 120Hz, carregamento instantâneo e gatilhos adaptativos.",
    destaques: [
      "SSD de 1TB — carrega em segundos",
      "Dois controles DualSense inclusos",
      "4K até 120Hz com HDR",
      "Garantia Sony de 12 meses",
    ],
    ficha: [
      { rotulo: "Armazenamento", valor: "SSD 1TB" },
      { rotulo: "Resolução", valor: "4K até 120Hz" },
      { rotulo: "Leitor de disco", valor: "Blu-ray Ultra HD" },
      { rotulo: "Controles", valor: "2x DualSense" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
  {
    id: "p02",
    slug: "console-ps5-slim-digital-1tb",
    sku: "8413-PS5D",
    nome: "Console PlayStation 5 Slim Digital 1TB",
    marca: "Sony",
    categoria: "consoles",
    forma: "console",
    precoDe: 3999,
    preco: 3199,
    custo: 2650,
    estoque: 18,
    estoqueAlvo: 50,
    nota: 4.8,
    avaliacoes: 736,
    selos: ["frete-gratis"],
    resumo:
      "Versão sem leitor de disco, mesmo desempenho. Ideal para quem já compra os jogos direto na PS Store.",
    destaques: [
      "SSD de 1TB",
      "Mais leve e compacto",
      "1 controle DualSense incluso",
      "Garantia Sony de 12 meses",
    ],
    ficha: [
      { rotulo: "Armazenamento", valor: "SSD 1TB" },
      { rotulo: "Resolução", valor: "4K até 120Hz" },
      { rotulo: "Leitor de disco", valor: "Não possui" },
      { rotulo: "Controles", valor: "1x DualSense" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
  {
    id: "p03",
    slug: "console-ps5-pro-2tb",
    sku: "8420-PS5P",
    nome: "Console PlayStation 5 Pro 2TB",
    marca: "Sony",
    categoria: "consoles",
    forma: "console",
    precoDe: 6799,
    preco: 5999,
    custo: 5100,
    estoque: 6,
    estoqueAlvo: 40,
    nota: 4.9,
    avaliacoes: 218,
    selos: ["lancamento"],
    resumo:
      "GPU 45% mais rápida, ray tracing avançado e upscaling por IA. O topo de linha da Sony para quem joga em TV 4K de verdade.",
    destaques: [
      "SSD de 2TB",
      "Ray tracing avançado",
      "Upscaling PSSR por IA",
      "Wi-Fi 7",
    ],
    ficha: [
      { rotulo: "Armazenamento", valor: "SSD 2TB" },
      { rotulo: "GPU", valor: "45% mais rápida que o PS5" },
      { rotulo: "Conectividade", valor: "Wi-Fi 7" },
      { rotulo: "Controles", valor: "1x DualSense" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
  {
    id: "p04",
    slug: "console-xbox-series-x-1tb",
    sku: "9110-XSX",
    nome: "Console Xbox Series X 1TB",
    marca: "Microsoft",
    categoria: "consoles",
    forma: "console",
    precoDe: 4499,
    preco: 3799,
    custo: 3200,
    estoque: 23,
    estoqueAlvo: 45,
    nota: 4.7,
    avaliacoes: 512,
    selos: ["frete-gratis"],
    resumo:
      "O console mais potente da Microsoft. 12 teraflops, 4K nativo e retrocompatibilidade com quatro gerações de jogos.",
    destaques: [
      "SSD de 1TB",
      "12 TFLOPS de GPU",
      "4K a 120Hz",
      "Retrocompatível",
    ],
    ficha: [
      { rotulo: "Armazenamento", valor: "SSD 1TB" },
      { rotulo: "GPU", valor: "12 TFLOPS" },
      { rotulo: "Resolução", valor: "4K até 120Hz" },
      { rotulo: "Controles", valor: "1x Xbox Wireless" },
      { rotulo: "Garantia", valor: "12 meses Microsoft" },
    ],
    fornecedor: "Microsoft Brasil",
  },
  {
    id: "p05",
    slug: "iphone-15-128gb",
    sku: "5501-IP15",
    nome: "Apple iPhone 15 128GB",
    marca: "Apple",
    categoria: "celulares",
    forma: "celular",
    precoDe: 5299,
    preco: 4299,
    custo: 3700,
    estoque: 31,
    estoqueAlvo: 60,
    nota: 4.9,
    avaliacoes: 2107,
    selos: ["mais-vendido", "frete-gratis"],
    resumo:
      "Chip A16 Bionic, Dynamic Island e câmera de 48MP. Entrada USB-C e bateria para o dia inteiro.",
    destaques: [
      "Tela Super Retina XDR de 6,1”",
      "Câmera principal de 48MP",
      "Chip A16 Bionic",
      "USB-C",
    ],
    ficha: [
      { rotulo: "Tela", valor: "6,1” Super Retina XDR" },
      { rotulo: "Processador", valor: "A16 Bionic" },
      { rotulo: "Câmera", valor: "48MP + 12MP ultra-angular" },
      { rotulo: "Armazenamento", valor: "128GB" },
      { rotulo: "Garantia", valor: "12 meses Apple" },
    ],
    fornecedor: "Apple Distribuição",
  },
  {
    id: "p06",
    slug: "galaxy-s24-256gb",
    sku: "5610-S24",
    nome: "Samsung Galaxy S24 256GB",
    marca: "Samsung",
    categoria: "celulares",
    forma: "celular",
    precoDe: 4999,
    preco: 3899,
    custo: 3300,
    estoque: 27,
    estoqueAlvo: 55,
    nota: 4.8,
    avaliacoes: 1493,
    selos: ["frete-gratis"],
    resumo:
      "Galaxy AI, tela Dynamic AMOLED 2X de 120Hz e câmera de 50MP com zoom óptico de 3x.",
    destaques: [
      "Galaxy AI integrado",
      "Tela 120Hz Dynamic AMOLED 2X",
      "Câmera de 50MP",
      "256GB de armazenamento",
    ],
    ficha: [
      { rotulo: "Tela", valor: "6,2” Dynamic AMOLED 2X 120Hz" },
      { rotulo: "Processador", valor: "Exynos 2400" },
      { rotulo: "Câmera", valor: "50MP + 12MP + 10MP" },
      { rotulo: "Armazenamento", valor: "256GB" },
      { rotulo: "Garantia", valor: "12 meses Samsung" },
    ],
    fornecedor: "Samsung Brasil",
  },
  {
    id: "p07",
    slug: "redmi-note-13-pro-256gb",
    sku: "5720-RN13",
    nome: "Xiaomi Redmi Note 13 Pro 256GB",
    marca: "Xiaomi",
    categoria: "celulares",
    forma: "celular",
    precoDe: 2199,
    preco: 1699,
    custo: 1320,
    estoque: 64,
    estoqueAlvo: 80,
    nota: 4.7,
    avaliacoes: 3241,
    selos: ["mais-vendido"],
    resumo:
      "Câmera de 200MP, carregamento de 67W e tela AMOLED de 120Hz. O custo-benefício que mais sai da loja.",
    destaques: [
      "Câmera de 200MP",
      "Carregamento turbo de 67W",
      "Tela AMOLED 120Hz",
      "8GB de RAM",
    ],
    ficha: [
      { rotulo: "Tela", valor: "6,67” AMOLED 120Hz" },
      { rotulo: "Processador", valor: "Snapdragon 7s Gen 2" },
      { rotulo: "Câmera", valor: "200MP + 8MP + 2MP" },
      { rotulo: "Armazenamento", valor: "256GB / 8GB RAM" },
      { rotulo: "Garantia", valor: "12 meses Xiaomi" },
    ],
    fornecedor: "Xiaomi Importação",
  },
  {
    id: "p08",
    slug: "moto-edge-50-fusion-256gb",
    sku: "5810-ME50",
    nome: "Motorola Edge 50 Fusion 256GB",
    marca: "Motorola",
    categoria: "celulares",
    forma: "celular",
    precoDe: 2499,
    preco: 1899,
    custo: 1480,
    estoque: 12,
    estoqueAlvo: 50,
    nota: 4.6,
    avaliacoes: 874,
    selos: [],
    resumo:
      "Tela curva pOLED de 144Hz, câmera de 50MP com OIS e bateria de 5000mAh com carga de 68W.",
    destaques: [
      "Tela curva pOLED 144Hz",
      "Câmera de 50MP com OIS",
      "Bateria de 5000mAh",
      "Resistente a água IP68",
    ],
    ficha: [
      { rotulo: "Tela", valor: "6,7” pOLED 144Hz" },
      { rotulo: "Processador", valor: "Snapdragon 7s Gen 2" },
      { rotulo: "Câmera", valor: "50MP OIS + 13MP" },
      { rotulo: "Armazenamento", valor: "256GB / 8GB RAM" },
      { rotulo: "Garantia", valor: "12 meses Motorola" },
    ],
    fornecedor: "Motorola Mobility",
  },
  {
    id: "p09",
    slug: "notebook-gamer-nitro-v15-rtx-4050",
    sku: "3301-NTV15",
    nome: "Notebook Gamer Acer Nitro V15 RTX 4050",
    marca: "Acer",
    categoria: "notebooks",
    forma: "notebook",
    precoDe: 5999,
    preco: 4899,
    custo: 4150,
    estoque: 15,
    estoqueAlvo: 40,
    nota: 4.7,
    avaliacoes: 621,
    selos: ["frete-gratis"],
    resumo:
      "RTX 4050 de 6GB, Core i5 de 13ª geração e tela de 144Hz. Roda os lançamentos em alto sem engasgo.",
    destaques: [
      "GeForce RTX 4050 6GB",
      "Tela 15,6” Full HD 144Hz",
      "16GB RAM / SSD 512GB",
      "Teclado retroiluminado",
    ],
    ficha: [
      { rotulo: "Placa de vídeo", valor: "RTX 4050 6GB" },
      { rotulo: "Processador", valor: "Intel Core i5-13420H" },
      { rotulo: "Memória", valor: "16GB DDR5" },
      { rotulo: "Armazenamento", valor: "SSD NVMe 512GB" },
      { rotulo: "Garantia", valor: "12 meses Acer" },
    ],
    fornecedor: "Acer do Brasil",
  },
  {
    id: "p10",
    slug: "macbook-air-m3-13-256gb",
    sku: "3410-MBA3",
    nome: 'Apple MacBook Air M3 13" 256GB',
    marca: "Apple",
    categoria: "notebooks",
    forma: "notebook",
    precoDe: 9999,
    preco: 8299,
    custo: 7300,
    estoque: 8,
    estoqueAlvo: 30,
    nota: 4.9,
    avaliacoes: 442,
    selos: [],
    resumo:
      "Chip M3, 18 horas de bateria e apenas 1,24kg. Silencioso, sem ventoinha, com tela Liquid Retina.",
    destaques: [
      "Chip Apple M3",
      "Até 18h de bateria",
      "Tela Liquid Retina 13,6”",
      "1,24kg, sem ventoinha",
    ],
    ficha: [
      { rotulo: "Processador", valor: "Apple M3 8-core" },
      { rotulo: "Memória", valor: "8GB unificada" },
      { rotulo: "Armazenamento", valor: "SSD 256GB" },
      { rotulo: "Tela", valor: "13,6” Liquid Retina" },
      { rotulo: "Garantia", valor: "12 meses Apple" },
    ],
    fornecedor: "Apple Distribuição",
  },
  {
    id: "p11",
    slug: "dell-inspiron-15-i5-512gb",
    sku: "3520-DI15",
    nome: "Dell Inspiron 15 Core i5 512GB",
    marca: "Dell",
    categoria: "notebooks",
    forma: "notebook",
    precoDe: 4299,
    preco: 3299,
    custo: 2750,
    estoque: 22,
    estoqueAlvo: 45,
    nota: 4.5,
    avaliacoes: 388,
    selos: [],
    resumo:
      "Notebook de trabalho com Core i5 de 13ª geração, 16GB de RAM e tela antirreflexo. Windows 11 Pro instalado.",
    destaques: [
      "Core i5-1334U",
      "16GB RAM / SSD 512GB",
      "Tela 15,6” antirreflexo",
      "Windows 11 Pro",
    ],
    ficha: [
      { rotulo: "Processador", valor: "Intel Core i5-1334U" },
      { rotulo: "Memória", valor: "16GB DDR4" },
      { rotulo: "Armazenamento", valor: "SSD NVMe 512GB" },
      { rotulo: "Sistema", valor: "Windows 11 Pro" },
      { rotulo: "Garantia", valor: "12 meses Dell" },
    ],
    fornecedor: "Dell Computadores",
  },
  {
    id: "p12",
    slug: "lenovo-ideapad-3-ryzen-5",
    sku: "3630-LIP3",
    nome: "Lenovo IdeaPad 3 Ryzen 5 512GB",
    marca: "Lenovo",
    categoria: "notebooks",
    forma: "notebook",
    precoDe: 3199,
    preco: 2499,
    custo: 2020,
    estoque: 0,
    estoqueAlvo: 40,
    nota: 4.4,
    avaliacoes: 512,
    selos: [],
    resumo:
      "Entrada sólida para estudo e home office: Ryzen 5, 8GB de RAM e SSD de 512GB.",
    destaques: [
      "AMD Ryzen 5 7520U",
      "8GB RAM / SSD 512GB",
      "Tela 15,6” Full HD",
      "1,6kg",
    ],
    ficha: [
      { rotulo: "Processador", valor: "AMD Ryzen 5 7520U" },
      { rotulo: "Memória", valor: "8GB LPDDR5" },
      { rotulo: "Armazenamento", valor: "SSD 512GB" },
      { rotulo: "Sistema", valor: "Windows 11 Home" },
      { rotulo: "Garantia", valor: "12 meses Lenovo" },
    ],
    fornecedor: "Lenovo Brasil",
  },
  {
    id: "p13",
    slug: "jbl-boombox-3",
    sku: "7701-JBB3",
    nome: "Caixa de Som JBL Boombox 3",
    marca: "JBL",
    categoria: "audio",
    forma: "audio",
    precoDe: 3299,
    preco: 2499,
    custo: 1980,
    estoque: 19,
    estoqueAlvo: 40,
    nota: 4.8,
    avaliacoes: 967,
    selos: ["frete-gratis"],
    resumo:
      "180W de potência, 24 horas de bateria e à prova d'água IP67. A caixa que segura a festa inteira.",
    destaques: [
      "180W RMS",
      "24 horas de bateria",
      "À prova d'água IP67",
      "Powerbank integrado",
    ],
    ficha: [
      { rotulo: "Potência", valor: "180W RMS" },
      { rotulo: "Bateria", valor: "Até 24 horas" },
      { rotulo: "Proteção", valor: "IP67" },
      { rotulo: "Conexão", valor: "Bluetooth 5.3" },
      { rotulo: "Garantia", valor: "12 meses JBL" },
    ],
    fornecedor: "Harman JBL",
  },
  {
    id: "p14",
    slug: "jbl-charge-5",
    sku: "7710-JBC5",
    nome: "Caixa de Som JBL Charge 5",
    marca: "JBL",
    categoria: "audio",
    forma: "audio",
    precoDe: 1299,
    preco: 899,
    custo: 690,
    estoque: 53,
    estoqueAlvo: 70,
    nota: 4.8,
    avaliacoes: 4102,
    selos: ["mais-vendido"],
    resumo:
      "40W, 20 horas de bateria e IP67. Carrega o celular enquanto toca — a mais vendida da categoria.",
    destaques: [
      "40W RMS",
      "20 horas de bateria",
      "À prova d'água IP67",
      "Carrega o celular",
    ],
    ficha: [
      { rotulo: "Potência", valor: "40W RMS" },
      { rotulo: "Bateria", valor: "Até 20 horas" },
      { rotulo: "Proteção", valor: "IP67" },
      { rotulo: "Conexão", valor: "Bluetooth 5.1" },
      { rotulo: "Garantia", valor: "12 meses JBL" },
    ],
    fornecedor: "Harman JBL",
  },
  {
    id: "p15",
    slug: "jbl-flip-6",
    sku: "7720-JBF6",
    nome: "Caixa de Som JBL Flip 6",
    marca: "JBL",
    categoria: "audio",
    forma: "audio",
    precoDe: 899,
    preco: 649,
    custo: 490,
    estoque: 47,
    estoqueAlvo: 70,
    nota: 4.7,
    avaliacoes: 2856,
    selos: [],
    resumo:
      "Portátil de 30W com 12 horas de bateria. Cabe na mochila e aguenta chuva e areia.",
    destaques: [
      "30W RMS",
      "12 horas de bateria",
      "À prova d'água IP67",
      "PartyBoost",
    ],
    ficha: [
      { rotulo: "Potência", valor: "30W RMS" },
      { rotulo: "Bateria", valor: "Até 12 horas" },
      { rotulo: "Proteção", valor: "IP67" },
      { rotulo: "Conexão", valor: "Bluetooth 5.1" },
      { rotulo: "Garantia", valor: "12 meses JBL" },
    ],
    fornecedor: "Harman JBL",
  },
  {
    id: "p16",
    slug: "jbl-tune-770nc",
    sku: "7730-JT77",
    nome: "Fone JBL Tune 770NC Bluetooth",
    marca: "JBL",
    categoria: "audio",
    forma: "audio",
    precoDe: 899,
    preco: 599,
    custo: 445,
    estoque: 9,
    estoqueAlvo: 50,
    nota: 4.6,
    avaliacoes: 1338,
    selos: [],
    resumo:
      "Cancelamento de ruído adaptativo e 70 horas de bateria. Dobrável, com estojo incluso.",
    destaques: [
      "Cancelamento de ruído adaptativo",
      "70 horas de bateria",
      "Dobrável com estojo",
      "Multiponto Bluetooth",
    ],
    ficha: [
      { rotulo: "Tipo", valor: "Over-ear fechado" },
      { rotulo: "Bateria", valor: "Até 70 horas" },
      { rotulo: "Cancelamento", valor: "ANC adaptativo" },
      { rotulo: "Conexão", valor: "Bluetooth 5.3 multiponto" },
      { rotulo: "Garantia", valor: "12 meses JBL" },
    ],
    fornecedor: "Harman JBL",
  },
  {
    id: "p17",
    slug: "controle-dualsense-ps5",
    sku: "8501-DS5",
    nome: "Controle Sem Fio DualSense PS5",
    marca: "Sony",
    categoria: "acessorios",
    forma: "controle",
    precoDe: 549,
    preco: 379,
    custo: 285,
    estoque: 88,
    estoqueAlvo: 120,
    nota: 4.9,
    avaliacoes: 5620,
    selos: ["mais-vendido"],
    resumo:
      "Gatilhos adaptativos, resposta háptica e microfone embutido. O acessório que mais sai da loja.",
    destaques: [
      "Gatilhos adaptativos",
      "Resposta háptica",
      "Microfone embutido",
      "Bateria recarregável",
    ],
    ficha: [
      { rotulo: "Compatibilidade", valor: "PS5, PC" },
      { rotulo: "Conexão", valor: "Bluetooth / USB-C" },
      { rotulo: "Bateria", valor: "Recarregável interna" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
  {
    id: "p18",
    slug: "controle-dualsense-edge",
    sku: "8510-DSE",
    nome: "Controle DualSense Edge PS5",
    marca: "Sony",
    categoria: "acessorios",
    forma: "controle",
    precoDe: 1499,
    preco: 1199,
    custo: 980,
    estoque: 11,
    estoqueAlvo: 35,
    nota: 4.7,
    avaliacoes: 312,
    selos: [],
    resumo:
      "Controle profissional: sticks substituíveis, botões traseiros e perfis salvos por jogo.",
    destaques: [
      "Módulos de stick substituíveis",
      "Botões traseiros",
      "Perfis por jogo",
      "Estojo rígido incluso",
    ],
    ficha: [
      { rotulo: "Compatibilidade", valor: "PS5, PC" },
      { rotulo: "Sticks", valor: "Módulos substituíveis" },
      { rotulo: "Perfis", valor: "Até 4 salvos" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
  {
    id: "p19",
    slug: "controle-dualshock-4-ps4",
    sku: "8420-DS4",
    nome: "Controle Sem Fio DualShock 4 PS4",
    marca: "Sony",
    categoria: "acessorios",
    forma: "controle",
    precoDe: 429,
    preco: 289,
    custo: 215,
    estoque: 5,
    estoqueAlvo: 60,
    nota: 4.8,
    avaliacoes: 4187,
    selos: [],
    resumo:
      "O clássico do PS4, com touchpad e alto-falante integrado. Funciona também no PC via Bluetooth.",
    destaques: [
      "Touchpad integrado",
      "Alto-falante e saída de fone",
      "Barra de luz",
      "Compatível com PC",
    ],
    ficha: [
      { rotulo: "Compatibilidade", valor: "PS4, PC" },
      { rotulo: "Conexão", valor: "Bluetooth / micro-USB" },
      { rotulo: "Bateria", valor: "Recarregável interna" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
  {
    id: "p20",
    slug: "headset-pulse-3d",
    sku: "8530-P3D",
    nome: "Headset Sem Fio Pulse 3D PS5",
    marca: "Sony",
    categoria: "acessorios",
    forma: "controle",
    precoDe: 749,
    preco: 549,
    custo: 430,
    estoque: 34,
    estoqueAlvo: 50,
    nota: 4.6,
    avaliacoes: 1092,
    selos: [],
    resumo:
      "Áudio 3D do PS5, microfones com cancelamento de ruído e 12 horas de bateria.",
    destaques: [
      "Áudio 3D nativo do PS5",
      "12 horas de bateria",
      "Microfones duplos com ANC",
      "Controles no fone",
    ],
    ficha: [
      { rotulo: "Compatibilidade", valor: "PS5, PS4, PC" },
      { rotulo: "Bateria", valor: "Até 12 horas" },
      { rotulo: "Conexão", valor: "USB sem fio" },
      { rotulo: "Garantia", valor: "12 meses Sony" },
    ],
    fornecedor: "Sony Brasil",
  },
];

/** Peso relativo de venda de cada produto — define o ranking do Analytics. */
export const PESO_VENDA: Record<string, number> = {
  p01: 9,
  p02: 5,
  p03: 2,
  p04: 4,
  p05: 8,
  p06: 6,
  p07: 11,
  p08: 4,
  p09: 5,
  p10: 2,
  p11: 3,
  p12: 3,
  p13: 4,
  p14: 12,
  p15: 8,
  p16: 5,
  p17: 14,
  p18: 2,
  p19: 7,
  p20: 4,
};

export const FORNECEDORES = [
  "Sony Brasil",
  "Microsoft Brasil",
  "Apple Distribuição",
  "Samsung Brasil",
  "Xiaomi Importação",
  "Motorola Mobility",
  "Acer do Brasil",
  "Dell Computadores",
  "Lenovo Brasil",
  "Harman JBL",
];
